name: DerpAchievments
version: '${project.version}'
main: net.derp.derpachievments.DerpAchievments
api-version: 1.17
depend: [ UltimateAdvancementAPI ]
authors: [ ThatBigDerp, GameDevX ]
description: That is adding the DUMBEST from the DUMBEST achievments...
